#!/bin/bash
#
# This script aims to automate (as much as is possible) performing a new linux install
# in tandem with mdadm software raid since most installers lack that option
#
# YMMV

# get os ID {neon, debian etc)
function get_os_id() {
  if [ -f /etc/os-release ]; then
    . /etc/os-release
    return "${ID}"
  else
    error_exit "[$red!$reset] The OS type cannot be determined, /etc/os-release not found!" 1
  fi
}

# takes two parms: string to display and int as exit code
function error_exit() {
  printf "%s" "${1}"
  exit "${2}"
}

# main thread
function main() {
  # set color codes for text
  red='\033[31m'
  green='\033[32m'
  reset='\033[0m'

  # first things first, detect OS for compat
  get_os_id
  if [[ $ID == "neon"   ]]; then
    echo "The ID is neon"
  elif [[ $ID == "ubuntu"   ]]; then
      echo "The ID is ubuntu"
  else
      error_exit
  fi
}

main "$@"
